# Generated by Django 6.0.1 on 2026-02-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userordersmodel',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='userordersmodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
