# Generated by Django 6.0.1 on 2026-02-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_userordersmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userordersmodel',
            name='payment_type',
            field=models.CharField(default='cash on delivery', max_length=100),
            preserve_default=False,
        ),
    ]
