# Generated by Django 6.0.1 on 2026-02-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userordersmodel_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userordersmodel',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userordersmodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='AllOrderedProducts',
        ),
    ]
