# Generated by Django 6.0.1 on 2026-02-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userordersmodel_product_id_userordersmodel_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userordersmodel',
            name='payment_id',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
