# Generated by Django 6.0.1 on 2026-02-23 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_userordersmodel_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userordersmodel',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.addreddmodel'),
        ),
    ]
