# Generated by Django 6.0.1 on 2026-02-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userordersmodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userordersmodel',
            name='payment_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
