# Generated by Django 6.0.1 on 2026-02-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_userordersmodel_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userordersmodel',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
