# Generated by Django 6.0.1 on 2026-02-26 04:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_userordersmodel_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custemusermodel',
            name='profile',
        ),
        migrations.AddField(
            model_name='custemusermodel',
            name='image',
            field=cloudinary.models.CloudinaryField(default='null', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
