# Generated by Django 6.0.1 on 2026-02-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_custemusermodel_profile_custemusermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addreddmodel',
            name='alter_nummber',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addreddmodel',
            name='primary_nummber',
            field=models.BigIntegerField(),
        ),
    ]
