# Generated by Django 6.0.1 on 2026-02-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_productmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='descount',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='stock',
            field=models.IntegerField(default=100),
        ),
    ]
